### ISSUE TITLE
Find libraries

### ISSUE THREAD

**Issue by mezgoodle** [mezgoodle/auto-formatter#10]
Find libraries which can format for different languages

**Comment by mezgoodle** [comment]
nodejs - eslint
python - autopep8

**Comment by Dmytrenko-Roman** [comment]
**CSS:** stylelint
**Install:** npm install --save-dev stylelint stylelint-config-standard
**Usage:** 
- Create a .stylelintrc.json configuration file in the root of your project.
- Fix: npx stylelint "**/*.css" --fix

**Comment by Dmytrenko-Roman** [comment]
**MARKDOWN:** markdownlint
**Install:**
- _markdownlint:_ npm install markdownlint --save-dev
- _markdownlint-cli:_ npm install -g markdownlint-cli
**Usage:**
- Fix problems: markdownlint **/*.md --ignore node_modules --fix

**Comment by Dmytrenko-Roman** [comment]
**NODEJS:** eslint
**Install**: npm install eslint --save-dev
**Usage:**
- Create a .json configuration file in the root of your project.
- Fix: npx eslint **/*.js --fix

**Comment by mezgoodle** [comment]
> **NODEJS:** eslint
> **Install**: npm install eslint --save-dev
> **Usage:**
> 
> * Create a .json configuration file in the root of your project.
> * Fix: npx eslint **/*.js --fix

After installed eslint we need type **npx**?
@Dmytrenko-Roman

**Comment by Dmytrenko-Roman** [comment]
### **PYTHON:** 
- Linter: autopep8
### **Install:** 
- pip install autopep8
### **Usage:**
- Fix problems: autopep8 --in-place --recursive --aggressive --agressive .

**Comment by Dmytrenko-Roman** [comment]
### **HTML:**
_Processing..._

**Comment by mezgoodle** [comment]
> ### **HTML:**
> * Linter: html-tidy
> 
> ### **Install:**
> * sudo apt install tidy
> 
> ### **Usage:**
> * tidy -m filename
> 
> _Verifying..._
> @mezgoodle

I still didn't test it, but will. Also look at this [library](https://www.npmjs.com/package/clean-html)
@Dmytrenko-Roman

**Comment by mezgoodle** [comment]
> > ### **HTML:**
> > 
> > * Linter: html-tidy
> > 
> > ### **Install:**
> > 
> > * sudo apt install tidy
> > 
> > ### **Usage:**
> > 
> > * tidy -m filename
> > 
> > _Verifying..._
> > @mezgoodle
> 
> I still didn't test it, but will. Also look at this [library](https://www.npmjs.com/package/clean-html)
> @Dmytrenko-Roman

### So

In our container we're using [alpine](https://alpinelinux.org/) instead of [ubuntu](https://ubuntu.com/). In **alpine** there isn't *tidy* package, [search result](https://pkgs.alpinelinux.org/packages?name=tidy&branch=edge). We can use some alternative for this package in **alpine** or use **clean-html** node library. Result of **CI** with **clean-html** you can see [here](https://github.com/mezgoodle/auto-formatter/pull/18). But there is one problem: in this library we need to set name of file and this is bad. If you can write **issue** to their repository of library with this question, please do it.
@Dmytrenko-Roman

**Comment by mezgoodle** [comment]
> ### **HTML:**
> * Linter: clean-html
> 
> ### **Install:**
> * ...
> 
> ### **Usage:**
> * ...
> 
> _Verifying..._
> @Dmytrenko-Roman

So, It's been a long time since you wrote this message🙂. I am currently working on python script, that searches for all **html** files and execute **clean-html** for them
Therefore, install command: `npm i -g clean-html`, usage: `clean-html <filename> --in-place`. You can edit your comment
