### ISSUE TITLE
git

### ISSUE THREAD

**Issue by mezgoodle** [mezgoodle/auto-formatter#4]
I tried to run `git checkout`, but got an [error](https://github.com/mezgoodle/auto-formatter/runs/939847370?check_suite_focus=true#step:3:342).

**Comment by mezgoodle** [comment]
test bot

**Comment by nyukers** [comment]
_fatal: not a git repository (or any of the parent directories): .git_
As for me the Git doesn't know here what it have to checkout.

**Comment by mezgoodle** [comment]
CI says that there is not an existing git-repo, so there is not _.git_ folder. So command `git status` outputs the same error
