### ISSUE TITLE
Many files

### ISSUE THREAD

**Issue by mezgoodle** [mezgoodle/auto-formatter#5]
We need something like _loop_ for these files: from [line 9](https://github.com/mezgoodle/auto-formatter/blob/master/action/Dockerfile#L9) to [line 17](https://github.com/mezgoodle/auto-formatter/blob/master/action/Dockerfile#L17)

**Comment by mezgoodle** [comment]
Make image from **imagine 100 files** and insert into main **Dockerfile**
@nyukers

**Comment by mezgoodle** [comment]
Also I liked this [line ](https://github.com/actionshub/terraform-lint/blob/master/Dockerfile#L3) from another _Dockefile_.

**Comment by nyukers** [comment]
> Make image from **imagine 100 files** and insert into main **Dockerfile**
> @nyukers

ok, I will try to build it.

**Comment by nyukers** [comment]
> Also I liked this [line ](https://github.com/actionshub/terraform-lint/blob/master/Dockerfile#L3) from another _Dockefile_.

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

**Comment by mezgoodle** [comment]
Execute several files

**Comment by nyukers** [comment]
I could run it via entrypoint.sh.  Pls, check output from gitstart.sh.

**Comment by nyukers** [comment]
Please, check my last result. So, it's not optimized code.

**Comment by mezgoodle** [comment]
> Please, check my last result. So, it's not optimized code.

Reviewed
